spring.application.name=order-service
server.port=8082
spring.datasource.url=jdbc:postgresql://postgres:5432/order_db
spring.datasource.username=dheeraj
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update